name: Sync to wiki

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Push changes
        run: |
          git remote add wiki https://andylolz:${{ secrets.GITHUB_TOKEN }}@github.com/andylolz/repo-wiki-sync.wiki.git
          git push --force wiki main:master
